version: "3.8"

services:
  threatlens:
    container_name: threatlens
    build:
      context: .
      dockerfile: Dockerfile
    image: threatlens:latest
    expose:
      - "8000"
    volumes:
      - .:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
  
  nginx:
    image: nginx:latest
    container_name: threatlens-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - threatlens
    restart: unless-stopped
