# Generated by Django 3.0.2 on 2025-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
